---
name: Bug report
title: 'Issue Title'
description: 'Report a bug with BeamLR'


body:
- type: markdown
  attributes:
    value: "## READ BEFORE CREATING ISSUE"
- type: markdown
  attributes:
    value: "### DO NOT CREATE ISSUES ABOUT THE MOD BEING BROKEN BY A BEAMNG UPDATE."
- type: markdown
  attributes:
    value: "### If the game has seen as major update (ex from 0.34 to 0.35) the mod will most likely break."
- type: markdown
  attributes:
    value: "### Be patient while I update the mod."
- type: markdown
  attributes:
    value: "## Issue Creation Guidelines"
- type: markdown
  attributes:
    value: "* Use english when creating issues. Use google translate if you don't speak english."
- type: markdown
  attributes:
    value: "* Before reporting an issue look at the **known issues** section of the main repository readme for a list of issues that cannot currently be fixed"
- type: markdown
  attributes:
    value: "* Attach log files, reproduction steps and any other information that can help fix the issue you are reporting. The more information you give the faster your issue will be fixed. Issues without log files, screenshots, reproduction steps, etc. are near impossible to fix."
- type: textarea
  id: repro
  attributes:
    label: Describe your issue
    description: "Describe the problem with as many details as possible, including reproduction steps, screenshots, log files, etc."
    value: "placeholder"
  validations:
    required: true    

---


  


